" Vim-Plug
call plug#begin('~/.vim/bundle')
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'scrooloose/nerdcommenter'
Plug 'szw/vim-tags'
Plug 'tpope/vim-sleuth'
Plug 'easymotion/vim-easymotion'
Plug 'majutsushi/tagbar'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-fugitive'
Plug 'Valloric/YouCompleteMe'
Plug 'w0ng/vim-hybrid'
Plug 'jiangmiao/auto-pairs'
Plug 'haya14busa/incsearch.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
call plug#end()

" Theme
set background=dark
colorscheme hybrid
let g:hybrid_custom_term_colors=1
let g:hybrid_reduced_contrast=1
let $NVIM_TUI_ENABLE_TRUE_COLOR=1

" Key bindings
let mapleader=','
inoremap jj <Esc>
inoremap <C-e> <Esc>A
inoremap <C-a> <Esc>I
nnoremap <C-n> :bnext<CR>
nnoremap <C-p> :bprevious<CR>
vmap <C-c> :w !pbcopy<CR><CR>
nnoremap ZQ :qa<CR>

" Basic Config
set number
set sw=2 ts=2 sts=2 et
set nowrap
set cursorline
set ignorecase
set smartcase
set showmatch

" Performance
set lazyredraw

" NerdTree
noremap  <leader>n :NERDTreeToggle<cr>
inoremap <leader>n <esc>:NERDTreeToggle<cr>

" Tagbar
nmap <leader>t :TagbarToggle<CR>

" fzf
let g:fzf_files_options=
  \ '--preview "(coderay {} || cat {}) 2> /dev/null | head -'.&lines.'"'

" incsearch
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)

" airline
let g:airline_theme='bubblegum'
let g:airline#extensions#tabline#enabled=1
let g:airline_powerline_fonts=1
set encoding=utf-8
set laststatus=2

if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif

let g:airline_left_sep = '⮀'
let g:airline_left_alt_sep = '⮁'
let g:airline_right_sep = '⮂'
let g:airline_right_alt_sep = '⮃'
let g:airline_symbols.branch = '⭠'
let g:airline_symbols.readonly = '⭤'
let g:airline_symbols.linenr = '⭡'

