" Vim-Plug
call plug#begin('~/.vim/bundle')
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'scrooloose/nerdcommenter'
Plug 'craigemery/vim-autotag'
Plug 'tpope/vim-sleuth'
Plug 'Shougo/unite.vim'
Plug 'Shougo/neomru.vim'
Plug 'Shougo/vimproc.vim', { 'do': 'make' }
call plug#end()

" Theme
colorscheme desert

" Key bindings
let mapleader = ","
inoremap jj <Esc>
inoremap <C-e> <Esc>A
inoremap <C-a> <Esc>I

" Basic Config
set number
set sw=2 ts=2 sts=2 et

" Unite configs
let g:unite_enable_start_insert = 1
let g:unite_source_grep_command = 'ag'
let g:unite_enable_ignore_case = 1
let g:unite_enable_smart_case = 1
let g:unite_source_grep_default_opts = '--nogroup --nocolor --column'
let g:unite_source_grep_recursive_opt = ''
nnoremap <silent> <leader>g :<C-u>Unite grep:. -buffer-name=search-buffer<CR>
nnoremap <silent> <leader>cg :<C-u>Unite grep:. -buffer-name=search-buffer<CR><C-R><C-W><CR>
nnoremap <silent> <leader>r :<C-u>UniteResume search-buffer<CR>

" NerdTree
noremap  <leader>n :NERDTreeToggle<cr>
inoremap <leader>n <esc>:NERDTreeToggle<cr>

