#
# User configuration sourced by interactive shells
#

# VI keymap
bindkey -v
bindkey '^R' history-incremental-search-backward
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
bindkey '^F' forward-char
bindkey '^B' backward-char
bindkey '^K' kill-line
bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^D' delete-char-or-list

VER="20170402"
DOTZSHDIR="$HOME/.dotfiles/zsh"

function loadsubconf()
{
    [[ -s $DOTZSHDIR/$1 ]] && {echo Loading $1 ...; . $DOTZSHDIR/$1}
}

echo Loading zsh ...

# Source zim
if [[ -s ${ZDOTDIR:-${HOME}}/.zim/init.zsh ]]; then
  source ${ZDOTDIR:-${HOME}}/.zim/init.zsh
fi

# Alias
alias reload='source ~/.zshrc'
alias ipython='ipython --pylab'

# Extension Alias
alias -s tgz='tar -zxvf'

# Options
autoload -U compinit
compinit -u

zstyle ':completion:*:default' menu select true
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

#autoload -U promptinit
#promptinit
#prompt adam2 cyan green magenta

zmodload -i zsh/mathfunc

HISTFILE=$DOTZSHDIR/zhistory
HISTSIZE=10000
SAVEHIST=20000

### We set some options here
setopt autocd
setopt hist_reduce_blanks hist_ignore_all_dups share_history appendhistory
setopt correct
setopt auto_pushd
setopt list_packed
setopt complete_in_word auto_list auto_menu menu_complete
setopt multios
setopt extended_glob
setopt always_to_end
setopt bash_auto_list

case ${OSTYPE} in
    darwin*)
        loadsubconf zshrc.osx
        ;;
    *bsd*)
        loadsubconf zshrc.bsd
        ;;
    linux*)
        loadsubconf zshrc.nix
        ;;
esac

loadsubconf zshrc.private
loadsubconf zshrc.local

# Common Exporting
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export PAGER=less
export EDITOR=vim
export XDG_CONFIG_HOME=$HOME/.config

# load RVM function
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm

echo ZSH config $VER was loaded, enjoy it.

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

