VER="20170402"
DOTZSHDIR="$HOME/dotfiles/zsh"

function loadsubconf()
{
    [[ -s $DOTZSHDIR/$1 ]] && {echo Loading $1 ...; . $DOTZSHDIR/$1}
}

echo Loading zsh ...

# Alias
alias reload='source ~/.zshrc'

alias ns=kubens
alias c=kubectx
alias k=tubectl

alias kd='tubectl describe'
alias kg='tubectl get'
alias kgp='tubectl get pod -owide'
alias ke='tubectl edit'
alias keti='tubectl exec -ti'

alias lv='list-servers-gcp.sh -v -f'
alias 1="awk '{print \$1}'"
alias 2="awk '{print \$2}'"
alias 3="awk '{print \$3}'"
alias 4="awk '{print \$4}'"
alias 5="awk '{print \$5}'"
alias 6="awk '{print \$6}'"
alias 7="awk '{print \$7}'"
alias 8="awk '{print \$8}'"
alias 9="awk '{print \$9}'"

#zstyle ':completion:*:default' menu select true
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

#autoload -U promptinit
#promptinit
#prompt adam2 cyan green magenta

zmodload -i zsh/mathfunc

HISTFILE=$DOTZSHDIR/zhistory
HISTSIZE=10000
SAVEHIST=20000

### We set some options here
setopt autocd
setopt hist_reduce_blanks hist_ignore_all_dups share_history appendhistory
setopt correct
setopt auto_pushd
setopt list_packed
setopt complete_in_word auto_list
setopt multios
setopt extended_glob
setopt always_to_end
setopt bash_auto_list
setopt magicequalsubst

case ${OSTYPE} in
    darwin*)
        loadsubconf zshrc.osx
        ;;
    *bsd*)
        loadsubconf zshrc.bsd
        ;;
    linux*)
        loadsubconf zshrc.nix
        ;;
esac

# Common Exporting
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export PAGER=less
export EDITOR=vim
export XDG_CONFIG_HOME=$HOME/.config

# load RVM function
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm
export PATH=$HOME/.rvm/bin:$PATH

# Source zim
# Start configuration added by Zim install {{{
#
# User configuration sourced by interactive shells
#

# -----------------
# Zsh configuration
# -----------------

#
# History
#

# Remove older command from the history if a duplicate is to be added.
setopt HIST_IGNORE_ALL_DUPS

#
# Input/output
#

# Set editor default keymap to emacs (`-e`) or vi (`-v`)
bindkey -e

# Prompt for spelling correction of commands.
#setopt CORRECT

# Customize spelling correction prompt.
#SPROMPT='zsh: correct %F{red}%R%f to %F{green}%r%f [nyae]? '

# Remove path separator from WORDCHARS.
WORDCHARS=${WORDCHARS//[\/]}


# --------------------
# Module configuration
# --------------------

#
# completion
#

# Set a custom path for the completion dump file.
# If none is provided, the default ${ZDOTDIR:-${HOME}}/.zcompdump is used.
#zstyle ':zim:completion' dumpfile "${ZDOTDIR:-${HOME}}/.zcompdump-${ZSH_VERSION}"

#
# git
#

# Set a custom prefix for the generated aliases. The default prefix is 'G'.
#zstyle ':zim:git' aliases-prefix 'g'

#
# input
#

# Append `../` to your input for each `.` you type after an initial `..`
#zstyle ':zim:input' double-dot-expand yes

#
# termtitle
#

# Set a custom terminal title format using prompt expansion escape sequences.
# See http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Simple-Prompt-Escapes
# If none is provided, the default '%n@%m: %~' is used.
#zstyle ':zim:termtitle' format '%1~'

#
# zsh-autosuggestions
#

# Customize the style that the suggestions are shown with.
# See https://github.com/zsh-users/zsh-autosuggestions/blob/master/README.md#suggestion-highlight-style
#ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=10'

#
# zsh-syntax-highlighting
#

# Set what highlighters will be used.
# See https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters.md
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

# Customize the main highlighter styles.
# See https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/main.md#how-to-tweak-it
#typeset -A ZSH_HIGHLIGHT_STYLES
#ZSH_HIGHLIGHT_STYLES[comment]='fg=10'

# ------------------
# Initialize modules
# ------------------

if [[ ${ZIM_HOME}/imfw.zsh -ot ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
  # Update static initialization script if it's outdated, before sourcing it
  source ${ZIM_HOME}/zimfw.zsh init -q
fi

# ------------------------------
# Post-init module configuration
# ------------------------------

#
# zsh-history-substring-search
#

# Bind ^[[A/^[[B manually so up/down works both before and after zle-line-init
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Bind up and down keys
zmodload -F zsh/terminfo +p:terminfo
if [[ -n ${terminfo[kcuu1]} && -n ${terminfo[kcud1]} ]]; then
  bindkey ${terminfo[kcuu1]} history-substring-search-up
  bindkey ${terminfo[kcud1]} history-substring-search-down
fi

bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down
# }}} End configuration added by Zim install

#
# User configuration sourced by interactive shells
#
# VI keymap
bindkey -v
bindkey '^R' history-incremental-search-backward
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
bindkey '^F' forward-char
bindkey '^B' backward-char
bindkey '^K' kill-line
bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^D' delete-char-or-list
bindkey '^W' backward-kill-word
bindkey '^U' vi-kill-line

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

loadsubconf zshrc.plugin

source <(kubectl completion zsh)
compdef tubectl=kubectl

loadsubconf zshrc.private
loadsubconf zshrc.local

echo ZSH config $VER was loaded, enjoy it.
